### PR TITLE
ML Tutorial: Fundamentals and Architectures

### PR DESCRIPTION
**Pull request by stockeh**
Notebook covering machine learning fundamentals and architectures for different data modalities, including **tabular**, **image**, and **time series** data. Added a subdirectory for the ml tutorial notebooks and associated images.

There are two datasets that need to be downloaded, with a default directory of `DATA_DIR = '~/d4-mldata'`

Some of the examples take up to 20 seconds to run on my laptop. This does slow down the `jupyter-book build book` command, and I'm not sure how this will impact the workflow of others.

### CODE REVIEW

**Comment by stockeh** [comment]
@djgagne awesome work getting this to run properly! It would be nice if we could somehow suppress the output of `datasets.MNIST` so the progress statements aren't overwhelming the notebook. Perhaps temporarily changing the log level?

**Comment by djgagne** [comment]
@stockeh Your notebook tutorial now builds and deploys, but part of the process is running all the code cells, which takes almost 6 and a half minutes, and that was after I made some of the notebook pieces smaller. Can you try to reduce the training times for some of the models by using simpler settings? It might also be a good idea to split the notebook into two or three that cover beginner and more advanced ML, or for some of the more complex models switch the cells over to markdown instead of executable Python.

**Comment by stockeh** [comment]
> @djgagne awesome work getting this to run properly! It would be nice if we could somehow suppress the output of `datasets.MNIST` so the progress statements aren't overwhelming the notebook. Perhaps temporarily changing the log level?

This will do the trick!

```python
import os
import sys
import contextlib

@contextlib.contextmanager
def suppress_output():
    with open(os.devnull, "w") as devnull:
        old_stdout = sys.stdout
        old_stderr = sys.stderr
        sys.stdout = devnull
        sys.stderr = devnull
        try:
            yield
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr
            
...
# Suppress tqdm output while loading the MNIST dataset
with suppress_output():
    mnist_train = datasets.MNIST(root=DATA_DIR, train=True,  download=True)
    mnist_test = datasets.MNIST(root=DATA_DIR, train=False, download=True)
```

**Comment by stockeh** [comment]
> @stockeh Your notebook tutorial now builds and deploys, but part of the process is running all the code cells, which takes almost 6 and a half minutes, and that was after I made some of the notebook pieces smaller. Can you try to reduce the training times for some of the models by using simpler settings? It might also be a good idea to split the notebook into two or three that cover beginner and more advanced ML, or for some of the more complex models switch the cells over to markdown instead of executable Python.

We decided to reduce training complexity (e.g., epochs, architecture, etc.) to speed up execution. Will keep in the same notebook and cover mostly **tabular** examples in the live tutorial.

**Review by djgagne — APPROVED** [review]
Everything builds and the notebooks run in a reasonable amount of time now. Merging.

**Pull request merged**
