### PR TITLE
teams update

### PR DESCRIPTION
**Pull request by mvernik1**
added GitHub repo to each team's page, changed team order to match website

### CODE REVIEW

**Comment by djgagne** [comment]
@mvernik1 I just pulled the changes from the main branch into this branch. If you run `git pull` on your local machine, the changes should then sync up. I didn't see any conflicts on my end.

**Review by djgagne — APPROVED** [review]
The changes look good to me. Merging.

**Comment by mvernik1** [comment]
Great, thanks @djgagne. The changes aren't showing up yet, do we need to push them manually or just give it some time?

**Comment by djgagne** [comment]
Can you check again? The updated team pages are appearing for me.

**Comment by mvernik1** [comment]
Yes, now they're appearing. Maybe it just needed some time. Thanks!

**Pull request merged**
